### ISSUE TITLE
Duplicated CSS

### ISSUE THREAD

**Issue by martoio** [Belul15/prj-rev-bwfs-dasmoto#5]
Notice how this code repeats 3 times?
https://github.com/Belul15/prj-rev-bwfs-dasmoto/blob/2e9f26e3e475f5de44c161ddc901a1d6a211bcd1/Dasmotos%20Art%26Craft/Resource/CSS/style.css#L21-L23

Now imagine the situation where the designer decides to change the font-size from 32px to 40px. (Also, don't forget to include the units `px`). You now need to make 3 changes just to change the font-size. Try to use classes to pull out the duplicate code into its own separate CSS rule.

Example:
```css
section h2{
    font-size: 32px;
    color: white;
    font-weight: bold;
}
```
